spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQA7RO2llQdtvUckbcnZtbBIAXbUntiLIDSy80VCTOXESz5T0mLnZkh+7+6GKg585AgOp6RDLGlhRr4O0vGJXcZRIi2Tgz/ImXjFZUPmSN2DFgDhYTp7kye4mvzgok6bSROwKvOzQ3tqS7r31rzmI6pxC/g9r7jORS0OchGk9lqil39GnS0zMvfP8R0j8cKAtJEVmrY4EetTtmrLj975Z57u1sNAJG/XO7sioXvS/MqfPCLkCT654TVGermqvaK+eWaPa/+dIhO9bPTvlz84dK21XuSVvFNcxnbFf/x/gZZlfMfz2iBQvQKz+SWcLzkbPZqA/oHqNbgXjfAqP862X+9X6xjqT6JWorGZ9CgjRHZzVsqnpYairi081PPARBl19nw='

token:
  expiration_time: 86400000
  secret: '{cipher}AQBZgUVbNh5E6eOxHlJctbeL5TjtKvECVJzL6lctloIdJzZd+SWAqX1koxbraVIK1Atu5t9TWjFJdb8JJOGZoSthGieY3E0Lm10IaWL58hE9FAN2OWH+U3k899Q9xt/c4YaTxWK8PpqIdUvzmNasiabyBAo18hD+XPVZlxfB3EQplcp9mTFyi7YMQ39PWx25GLqZfJW7QlRWG3Op/cy9oxmACmhOkytGbpIObX0auqjLDqcirTjGlKc89Q5UA0rsoyyA4YnN9KeZ7f5nFvCNtINsSqf57mU/KvgzTthLlR9lOYaDiiQf4eA3Xjc0fOXI7JT4o9j80mmGsEuTZMyDkbu0JZpLSt9Wv7CCLcuxozxxLXc3xl4d8JstNP4YawmaZPBY6JFUHsigeel/I34/iI19'

gateway:
  ip: 172.18.0.9

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: There is no item.
